- name: Install and run nginx
  become: yes
  hosts: web
  tasks:
  - name: nginx installation
    ansible.builtin.package: # module for install package
      name: nginx
      state: present    
    
  - name: start nginx  
    ansible.builtin.service: # module for start and enable the package
      name: nginx 
      state: started
      enabled: yes 